Translation
Racix/Project-AI-Translation pull request #50
Opened 2023-11-08 09:01 UTC by ClaudeHallard

Translation as a microservice using NLLB

2023-11-10 14:38 UTC, langemittbacken reviewed
gick igenom koden och la till lite ändringsförslag

2023-11-10 14:38 UTC, langemittbacken commented on backend/api/app/main.py
> +@app.post("/media/{media_id}/analysis/translate/{from_language}/{to_language}")
tror vi diskuterade på mötet ta bort {from_language} då det går att få ifrån transkriberingsresultatet.
jag skulle dock vilja ändra till post(/media/{media_id}/translate/{to_language}) då jag tycker att översättningen sker åtskilt från den "vanliga analysen" (ni andra får också säga om ni tycker bu eller bä om det)

2023-11-10 14:38 UTC, langemittbacken commented on backend/api/app/main.py
> +                    status_data = {"status": status.HTTP_200_OK, "message": "Translation done."}
borde status vara 201 kanske? jag ser att det är det på rad 216, blir det två sändningar? ska båda vara med?

2023-11-10 14:38 UTC, langemittbacken commented on backend/backend.sh
> +    docker compose -f $COMPOSE_FILE --compatibility up -d
misstag eller ska det ändras?

2023-11-12 08:44 UTC, ClaudeHallard commented on backend/api/app/main.py
> +@app.post("/media/{media_id}/analysis/translate/{from_language}/{to_language}")
Nya whisper modellen har inte language detect så jag låter from_language vara kvar.
Jag håller med!

2023-11-12 08:45 UTC, ClaudeHallard commented on backend/api/app/main.py
> +                    status_data = {"status": status.HTTP_200_OK, "message": "Translation done."}
(Y)

2023-11-12 08:45 UTC, ClaudeHallard commented on backend/backend.sh
> +    docker compose -f $COMPOSE_FILE --compatibility up -d
docker versioner som skiljer sig

2023-11-12 10:27 UTC, langemittbacken approved these changes
okej jag tycker det ser bra ut nu iaf!

2023-11-12 17:35 UTC, IsakLundstrom commented on backend/api/app/main.py
> +@app.post("/media/{media_id}/analysis/translate/{from_language}/{to_language}")
@ClaudeHallard Vad mennar du att den nya whisper modellen inte har language detect? Hur löser det sig då? Måste man ange språk eller? 

Sen i tycker i alla fall jag att det ska vara .../analysis/translate... för det är ju analysisen man translatar och man kan inte translata om man inte har en analys (hur som helst kommer det ju att fungera men jag tycker det är snyggare så)

2023-11-12 17:36 UTC, IsakLundstrom commented on backend/api/app/main.py
> +    status_data = {}
Allt med status data hade med `analysisManager` att göra så du bör kunna ta bort allt med status_data (om du inte tänkt använda det till något)

2023-11-12 17:43 UTC, IsakLundstrom commented on backend/api/app/main.py
> +def try_find_translation(media_id: str, language: str) -> dict[str, str]:
Flytta ner den här metoden till dem andra `try_...` metoderna + flytta ner translate metoderna 
 (post och get) under alla analysis metoderna (det blir mycket snyggare och lättare att hitta om funktionerna ligger på ett ordnat sätt)

2023-11-12 17:46 UTC, IsakLundstrom commented on backend/translation/app/main.py
> +@app.post("/translate", status_code=status.HTTP_201_CREATED)
varför inte använda `/translate/{from_language}/{to_language}` som du gjorde i api's main.py? (det här fungerar men undrar varför)

2023-11-12 17:53 UTC, IsakLundstrom requested changes
Fixa i alla fall status_data och flytta metoderna

2023-11-13 14:44 UTC, ClaudeHallard commented on backend/api/app/main.py
> +    status_data = {}
Borttaget

2023-11-13 14:45 UTC, ClaudeHallard commented on backend/api/app/main.py
> +def try_find_translation(media_id: str, language: str) -> dict[str, str]:
Jag håller med. Nu ser det lite bättre ut.

2023-11-13 14:47 UTC, IsakLundstrom approved these changes
👍

2023-11-14 14:17 UTC, merged