Whisper pip
Racix/Project-AI-Translation pull request #51
Opened 2023-11-11 12:45 UTC by hamidehsani54

Pipeline does not support detecting any language so this functionality has been removed.

2023-11-20 07:45 UTC, langemittbacken requested changes
har lite frågor om koden innan jag kan approva

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/Dockerfile
> +# ... (rest of your Dockerfile)
onödigt många tomrader och ta bort kommentaren som är kopierad från GPT

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/app/transcribe.py
> +MODEL_NAME3 = "openai/whisper-small"
varför just "MODEL_NAME3"? borde kunna döpas bättre

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/app/transcribe.py
> +
ta bort en rad

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/Dockerfile
> +COPY ./app /transcription/app
dublett av copy

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/app/transcribe.py
> +        transcription = whisper_pipeline(file_path, return_timestamps=True, chunk_length_s=30, batch_size=32, generate_kwargs={ "language": "en", "task": "transcribe"})
några rader ovan så detekterar vi språket, ska då skickas in engelska till pipelinen sen? det kanske inte spelar någon roll men vill veta vad ni har testat och upptäckt

2023-11-20 07:45 UTC, langemittbacken commented on backend/transcription/app/transcribe.py
> +            if start_timestamp is not None and end_timestamp is not None:
kastas resultatet för en sentence bara bort om det inte finns timestamps? borde förmodligen aldrig hända men kanske bra att gardera sig?

2023-11-20 09:24 UTC, Lundsak commented on backend/transcription/app/transcribe.py
> +            device="cpu",
Kanske värt att ha någon typ av parameter eller miljövariabel för att bestämma device.

2023-11-20 17:10 UTC, tonytonfisk2 commented
När man transkriberar svenska audio klipp får man tillbaka istället resultatet på engelska. Är det tanken?

2023-11-22 15:13 UTC, hamidehsani54 commented on backend/transcription/app/transcribe.py
> +            device="cpu",
Den är också fixad.

2023-11-22 15:13 UTC, hamidehsani54 commented on backend/transcription/app/transcribe.py
> +            if start_timestamp is not None and end_timestamp is not None:
Tog hand om den!

2023-11-22 15:24 UTC, langemittbacken commented on backend/transcription/app/transcribe.py
> +            device="cpu",
vad jag kan se råkade du ta bort device helt och hållet. Du har skapat en variabel men den används inte i whisper_pipeline = pipeline( ... )

2023-11-23 10:05 UTC, hamidehsani54 commented on backend/transcription/app/transcribe.py
> +            device="cpu",
> vad jag kan se råkade du ta bort device helt och hållet. Du har skapat en variabel men den används inte i whisper_pipeline = pipeline( ... )

Fixad!

2023-11-23 12:27 UTC, oskar-dah commented
Måste allt detta hämtas varje körning eller kan vi hämta detta när vi skapar containern?
Printout från docker 
![image](https://github.com/Racix/Project-AI-Translation/assets/61740163/bf9f82b3-fbc4-405f-a0b3-452cff43e6b1)

2023-11-24 10:55 UTC, hamidehsani54 commented
> Måste allt detta hämtas varje körning eller kan vi hämta detta när vi skapar containern? Printout från docker ![image](https://user-images.githubusercontent.com/61740163/285205490-bf9f82b3-fbc4-405f-a0b3-452cff43e6b1.png)

![image](https://github.com/Racix/Project-AI-Translation/assets/75583986/93ce3b9f-222f-4ea4-a210-411518a88286)
It should be solved.

2023-11-28 13:28 UTC, langemittbacken commented on backend/transcription/loadModel.py
> +model_size = "tiny"
används variabeln?

2023-11-29 10:10 UTC, hamidehsani54 commented on backend/transcription/loadModel.py
> +model_size = "tiny"
Har tagit bort variabeln som inte används.

2023-12-07 09:29 UTC, oskar-dah commented
This works on my machine running on CPU.

2023-12-08 04:24 UTC, tonytonfisk2 commented
> Hmm, can only run the small model size on GPU with 16gb vram, I get CUDA out of memory issues on the bigger models.
> 
> But otherwise the code seems to work.

Nevermind, removed batch_size parameter from pipeline can now run it in largev2 model size as well. Affects the speed a bit buts its fine.

can probably merge this PR now.

2023-12-09 14:20 UTC, hamidehsani54 commented
> > Hmm, can only run the small model size on GPU with 16gb vram, I get CUDA out of memory issues on the bigger models.
> > But otherwise the code seems to work.
> 
> Nevermind, removed batch_size parameter from pipeline can now run it in largev2 model size as well. Affects the speed a bit buts its fine.
> 
> can probably merge this PR now.

nice, then we can merge it to the main branch

2023-12-11 13:03 UTC, oskar-dah approved these changes

2023-12-11 13:03 UTC, merged